# Introduction to Numpy

`numpy` is arguably the most important/widely-used library in Python. It offers great performance and convinence in high-dimensional arrays, which is crucial to scientific computing.

We are going to focus on some basic operations, and some commonly used submodules.

Commonly, people import `numpy` and abbreviate it as `np`
```
import numpy as np
```

## As always, read [`numpy` documentations](https://docs.scipy.org/doc/numpy-1.14.0/index.html)

In [1]:
import numpy as np

## `array` vs. `list`

In [2]:
lst = [1, 2, 3] # python lst
print(type(lst))
a = np.array(lst, dtype=float) # numpy array, dtype: what is the data type of the elements 
print(type(a))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
a

array([ 1.,  2.,  3.])

## `array` creation

In [6]:
# 1. create from list, specify dtype
a = np.array(range(10), dtype=float)
# 2. use np.arange
a = np.arange(10, dtype=float)
b = np.arange(1, 10)
c = np.arange(10, 2, -2)

In [8]:
# 3. zeros, ones
z = np.zeros(4)
x = np.ones(10)

## `array.shape`

In [17]:
a = np.arange(12)
print(a.shape)
x = a.reshape((2, 6))
x

(12,)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

## Basic operations: axis

In [18]:
a = np.arange(12).reshape((3, 4))
# sum
sum_over_row = a.sum(axis=0) # axis=0 -> sum over the first dimension of the array, leaving the second dimension
sum_over_col = a.sum(axis=1) # axis=1 -> sum over the second dimension of the array, leaving the first dimension
print(sum_over_row)
print(sum_over_col)

[12 15 18 21]
[ 6 22 38]


## Try this question (hint: look at `numpy.linalg` module)

You are given a matrix with each row as a vector. Find the index of the row which has the smallest $L_2$ norm.
As a reference, for any vector $v$ , its $L_2$ norm is defined as:
$$ ||v||_2 = \sqrt{\sum_{i = 1}^{n}v_i^2}$$

In [24]:
A = np.array([1, 4, -2, 2])
np.argmin(A) # A.argmin()

2

In [ ]:
# your code here
def find_idx_smallest_norm(A):
    norms = np.linalg.norm(A, axis=1)
    return norms.argmin()